### ISSUE TITLE
False preferences ignored

### ISSUE THREAD

**Issue by ddugovic** [VirusLauncher/customizable-discordjs-pagination#12]
For example, `paginationCollector.disableEnd: false` does the same thing as `paginationCollector.disableEnd: true`.  #11 fixes my particular V14 concern.

**Comment by ddugovic** [comment]
But seriously, why create such a great library and not test it?

**Comment by VirusLauncher** [comment]
@ddugovic Hey, my apologies for the late response. I'm currently recreating the library somewhat like the EmbedBuilder from DiscordJS for the ease of use for the end user. #11 patch are fixed in the [Dev](/VirusLauncher/customizable-discordjs-pagination/tree/dev) branch and it will be merged in the main branch by the 14th.

**Comment by ddugovic** [comment]
Awesome, thanks for the response and thanks for helping me understand!  This is a great library and I'm glad to hear you're OK.
